# Generated by Django 5.1.7 on 2025-04-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
    ]
