# Generated by Django 5.1.7 on 2025-04-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20250405_0631'),
    ]

    operations = [
    ]
